### ISSUE TITLE
AB PLC plctag.dll check status in delphi example?

### ISSUE THREAD

**Issue by cristianocastelao** [libplctag/libplctag#147]
Does anyone have an example of communication using libplctag with tcp / ip and checking status in Delphi?

**Comment by kyle-github** [comment]
Hi, thanks for using the library.   You may have more luck asking this question on the forum https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/libplctag.

**Comment by kyle-github** [comment]
Have you had any luck with this?

**Comment by cristianocastelao** [comment]
I had no luck with that, but I developed in delphi using wtclient

**Comment by kyle-github** [comment]
Sorry to hear that you were not able to get the Pascal wrapper working, but good to hear that you found a solution!
