### ISSUE TITLE
plc_tag_get_debug_level()

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag#154]
[In the documentation](https://github.com/libplctag/libplctag/wiki/API#tag-internal-attribute-functions) it talks about being able to retrieve debug level by calling `plc_tag_get_debug_level()` but this function is not available.

This could be an issue either with the documentation or with the API.

**Comment by kyle-github** [comment]
Definitely a doc bug.

**Comment by kyle-github** [comment]
I think I have found all the references to plc_tag_get_debug_level() and removed them.   I also updated the code to support both attributes: 'debug_level' and 'debug' with a warning when you use 'debug_level'.

**Comment by timyhac** [comment]
Looks good Kyle, thanks for clarifying - I'll update the wrapper with the preferred naming.

**Comment by kyle-github** [comment]
The fix is in 2.1.10 IIRC, so it is not released yet.   I did update the API docs.

**Comment by kyle-github** [comment]
Yep, in the prerelease branch.   That has the new Modbus stuff in it too.

**Comment by kyle-github** [comment]
Fixed in release 2.1.10.
