### ISSUE TITLE
BUG, output log 'datetime' error on windows.

### ISSUE THREAD

**Issue by xieqiang15** [libplctag/libplctag#182]
'src\platform\windows\platform.c'.

int64_t time_ms(void)
{
    FILETIME ft;
    int64_t res;

    GetSystemTimeAsFileTime(&ft);

    /* calculate time as 100ns increments since Jan 1, 1601. */
    res = (int64_t)(ft.dwLowDateTime) + ((int64_t)(ft.dwHighDateTime) << 32);

    /* get time in ms */

    res = (res - 116444736000000000) / 10000;

    return  res;
}

**Comment by kyle-github** [comment]
Hi, thanks for the patch.

Can you set this up as a pull request?   This looks like a good patch.  Does it fix the problem where the logging output shows the year as 2389?

**Comment by xieqiang15** [comment]
Yes, the logging output shows the year as 2389.
Sorry, I won't set pull request.

**Comment by kyle-github** [comment]
I can rework this as a patch this weekend if you do not have access to do.

**Comment by kyle-github** [comment]
This seems to be fixed on the tip of the prerelease branch.   Thanks!

This also uncovered another bug: all the months were off by one.   The month printed as 7, but should be 8 for August.
