### ISSUE TITLE
AB protocol allows dealing with single tag only

### ISSUE THREAD

**Issue by GitHubDragonFly** [libplctag/libplctag#183]
Currently, I have to remove a tag before creating another tag and it's only 1 tag that can be used at the time.

Modbus protocol doesn't have that limitation, it allows creating a list of tags without removing tags.

Is it possible to restore that functionality as it was present in v2.1.6?

**Comment by kyle-github** [comment]
Hi, thanks for using the library and reporting this problem.

Can you please describe:

- which OS and compiler you are using?
- which type of PLC you are reading?
- which version of the library you are using?
- how you are getting the library binaries?   Are you building these or are you getting them from one of the releases?
- which, if any, wrapper language you are using?

Thanks.  These things will help us determine the cause of the problem!

**Comment by GitHubDragonFly** [comment]
What I stated is applicable to MicroLogix 1100 and v2.1.14 library binary from your release.

I just tried ControlLogix and it did allow creating a tag list, without removing tags, as well as access those from another thread.

Both of the above did work with v2.1.6 library binary from your release, including read/write access from another thread.

Modbus protocol, also from v2.1.14, does allow creating a tag list without removing tags but it just ignored read/write access from another thread.

It is Windows based app that I am using (Windows 10, Visual Studio 2019, modified C# wrapper from Mesta - updated to match some of the features from your latest library).

I am just testing your library and there is no machinery of any kind involved.

On a side note, from my tests and related to your code and some previous topics you had:
- Strings in MicroLogix 1100 are 84 bytes long and have bytes reversed (which might be the case for PLC5 as well)
- Custom length ControlLogix strings should be minimum 8 bytes in size, even if defined as a single character string, and the multiples of 8 afterwards and depending on the custom length So, the elem_size parameter should require user input (by knowing the length of the string as well as the number of bytes it fits in).

**Comment by kyle-github** [comment]
Thanks for the additional information.  I am not sure what you mean by a tag list.  I tried both the stress_test.c and async_stress.c programs with the latest release and pre-release versions and both support multiple tags without any problem.   stress_test.c uses multiple tags.   The test_auto_sync.c program tests some experimental features that are not relevant here, but tests them by using the same tag across multiple threads and that works fine as well.

Note that the Mesta wrapper has not been updated for a long time and should probably be considered stale at this point :-(  There is a new[ C#/.Net wrapper](https://github.com/libplctag/libplctag.NET) that is part of the libplctag GitHub organization.   It has not hit 1.0 yet, but is under heavy development.  It supports both .Net Core and .Net Framework.   IIRC, the original Mesta wrapper does not support MicroLogix at all.

Thanks for the updates on the MicroLogix.  I am currently working on support for strings in the C DLL.   This support will be very low level but will allow creating code to support strings that is mostly/completely PLC generic.  I may need to make some changes based on your points about custom ControlLogix strings.

**Comment by GitHubDragonFly** [comment]
Here is a part of Mesta's C# wrapper that creates a tag list (or dictionary entry) upon each successful pointer returned:

        public readonly Dictionary<string, Int32> _tags;

        public Libplctag()
        {
            _tags = new Dictionary<string, Int32>();
        }

        public void AddTag(Tag tag, int timeout)
        {
            var ptr = Plc_tag_create(tag.UniqueKey, timeout);          <--- crash occurs here
            _tags.Add(tag.UniqueKey, ptr);
        }

UniqueKey represents a full string in the form of: "protocol=ab_eip&gateway=192.168.0.100&cpu=SLC&elem_size={ELEM_SIZE}&elem_count={ELEM_COUNT}&name=F8:0&debug=1"

Currently, with MicroLogix 1100 and v2.1.14 of your library, an attempt to add a second tag crashes the app and is reported in Visual Studio as 0xc0000409 error (described on the Internet as STATUS_STACK_BUFFER_OVERRUN).

This is more or less irrelevant to me as I am just testing and can use the old v2.1.6 library.

Here is also a picture of the controller tag list, returned with your "@tags" addition to the library and displayed in the combobox visual control, which shows reported sizes for 1char and 20char custom length strings.

![Get Tag List](https://user-images.githubusercontent.com/69928501/90905361-13845900-e39e-11ea-8125-56e30f4e8822.png)

**Comment by GitHubDragonFly** [comment]
This is not really an issue, it was more of asking for the functionality that was existent previously.

There is no need to keep it open.

**Comment by kyle-github** [comment]
Hi, I'd like to keep this open until I can make sure it is fixed.   There isn't any specific functionality in the C DLL that changed for this between 2.1.6 and 2.1.14.   The error you reference seems to be

I do not have a MicroLogix but I do have a PLC/5.  I will see if I can recreate any of this there.   

Would it be possible to run your test with debugging turned on in the C DLL?   To do that, you can add "&debug=4" to the tag string or use the plc_tag_set_debug_level() function (if that is exposed, it might not be with the Mesta wrapper).

**Comment by kyle-github** [comment]
Some research about the error you see seems to point to a possible mismatch between the calling conventions used in PInvoke and C, or an infinite stack recursion.

The C routine plc_tag_create() takes two parameters: a C-style string using ASCII/UTF-8 encoding, and an integer.   On all Windows platforms (32 and 64-bit) of which I am aware, the integer parameter will be 32-bit.   The function returns a 32-bit signed integer.   If you can check the modified Mesta library, that might point to something incorrect in how it is declaring the interface to the C library.

The other option is that there is an infinite recursion happening.  The most likely spot is in the parsing of the tag string.  Is the tag string you showed above with partially-evaluated variables the actual tag string?  "protocol=ab_eip&gateway=192.168.0.100&cpu=SLC&elem_size={ELEM_SIZE}&elem_count={ELEM_COUNT}&name=F8:0&debug=1"   The "{ELEM_SIZE}" and "{ELEM_COUNT}" parts should be positive integers.

I will see if I can recreate any recursion in the C library.

Thanks again for reporting this problem.

**Comment by GitHubDragonFly** [comment]
If I compile your library by using Visual Studio and then import it into my app, the breakpoint is trigered in your platform.c file at this point:

 * str_cmp_i
 *
 * Returns -1, 0, or 1 depending on whether the first string is "less" than the
 * second, the same as the second, or "greater" than the second.  The comparison
 * is done case insensitive.
 *
 * It just passes this through to Windows stricmp.
 */
extern int str_cmp_i(const char *first, const char *second)
{
    return _stricmp(first,second);
}

The "first" has value while the "second" is null.

I am not sure what other file of yours this is called from.

**Comment by kyle-github** [comment]
Hmm, interesting.   That function is called all over the place.   I wonder if there is a recursive loop that ends up calling str_cmp_i() with NULL or if the recursion is in Microsoft's implementation of _stricmp()?

**Comment by kyle-github** [comment]
This was a very useful finding, thanks!   I will put in some guard code in places where I call through to Microsoft's C library functions.

**Comment by GitHubDragonFly** [comment]
Everything is happening in the session.c file, within ab folder, and in this order:

ab_session_p session_create_unsafe(const char *host, const char *path, plc_type_t plc_type, int *use_connected_msg)
- session path is set to null when the first tag is created
- creation of the second tag calls the "ab_session_p find_session_by_host_unsafe" method

ab_session_p find_session_by_host_unsafe(const char *host, const char *path)
- calls session_match_valid method by passing the path as a value

int session_match_valid(const char *host, const char *path, ab_session_p session)
{
    if(!session) {
        return 0;
    }

    /* don't use sessions that failed immediately. */
    if(session->failed) {
        return 0;
    }

    if(str_cmp_i(host, session->host)) {
        return 0;
    }

    if(str_cmp_i(path, session->path)) {                <--- passing a value for path and null for session->path
        return 0;
    }

    return 1;
}

**Comment by kyle-github** [comment]
I think you found the problem!   That code is part of the code that looks up the existing connections to PLCs to see if there is already one that matches the new tag.   If there are no other connections then the check is not done, which is why the first tag works.   Once there is a connection, then this comparison is hit.

This is in code that was tweaked recently to allow DH+ bridging  to work with MicroLogix and SLC, so this is definitely a regression.

Thanks very much for raising this bug!   I will work on a fix today.   I will go through all the platform code for Windows to make sure that I am checking for NULL arguments and other degenerate cases (that the Linux and macOS C libraries handle).

**Comment by GitHubDragonFly** [comment]
The path is string.empty and if you can set the session path to the same instead of null then it will work.

**Comment by kyle-github** [comment]
I was able to duplicate the problem with multiple tags and the current tip of the prerelease branch appears to fix it.   It passes all my tests as well as all the automated CI tests.   Thanks again for bringing this up and helping find the source of the problem!
