### ISSUE TITLE
communicate with the compactlogix l33er

### ISSUE THREAD

**Issue by leowoki** [libplctag/libplctag#224]
Is it possible to communicate with the compactlogix l33er?
The path is this: protocol=ab_eip&gateway=192.168.1.250&path=0,0&cpu=compactlogix&elem_size=2&elem_count=1&name=b1

**Comment by kyle-github** [comment]
If the tags are not protected, you should be fine.

**Comment by kyle-github** [comment]
Oops, rereading that, you might need a path of "1,0".   I do not have a CompactLogix handy but I think they have a static path.   You can leave out the elem_size if you want, it is optional.

**Comment by leowoki** [comment]
> Oops, rereading that, you might need a path of "1,0". I do not have a CompactLogix handy but I think they have a static path. You can leave out the elem_size if you want, it is optional.

Thank you. I will do the test next week and will send the results in the meantime.

**Comment by kyle-github** [comment]
Were you able to test this?

**Comment by leowoki** [comment]
> Were you able to test this?

Sorry, I was delayed by other things for a long time, but I finally got a chance to test it and it can communicate with the compactlogix l33er.

**Comment by kyle-github** [comment]
Good to hear that it is working for you.   Please reopen this if there are other problems.  Thanks for reaching out!
