### ISSUE TITLE
Python Wrapper

### ISSUE THREAD

**Issue by GitHubDragonFly** [libplctag/libplctag#228]
This is sort of an instructional post of how to use python wrapper in python3 on Windows and with a tkinter GUI.

The folder structure looks like in the attached picture, where the corresponding plctag libraries have been copied to their own folders (including Android libraries).

![Python plctag folder structure](https://user-images.githubusercontent.com/69928501/106981842-c79d5480-6730-11eb-9e7b-5aac5726358d.png)

The libplctag.py code was slightly modified for loading the C library on different systems (see the attached).
It works in Windows and in Pydroid 3 on Android but I'm not sure about the other.

[libplctag.py.zip](https://github.com/libplctag/libplctag/files/5994103/libplctag.py.zip)

The GUI interface/script was derived from the updated pylogix GUI example, which I recently completed.
These are pictures of the preliminary GUI:

![Python plctag GUI 1](https://user-images.githubusercontent.com/69928501/109412101-1034e000-7974-11eb-81d3-406b49e81080.png)

![Python plctag GUI 2](https://user-images.githubusercontent.com/69928501/109412102-1034e000-7974-11eb-95be-d63ce767a092.png)

It is my intention to eventually create a repository and include fully functional plctag_gui.py file.

**Comment by kyle-github** [comment]
Wow!  This is nice. I will try this on Linux this weekend and see if it works there too.   Do you want me to set up a libplctag.py repo in the libplctag project for you?   You have done so many great contributions, it would be good to have them more visible!  I am still underwater with the new event core and will be for a while.

**Comment by GitHubDragonFly** [comment]
I still intend to create my own repository with this since it makes it easier for me to maintain.
My repositories are generally intended as a self-serve place that only requires people to read instructions and use whatever they can.

On the other hand, you should create separate repositories within your organization, for each language, so you can have a better control and keep the relevant posts within each repository.

Neither of the following is your competition: AdvancedHMI, pylogix or me.
I contribute to libplctag and pylogix and AdvancedHMI with sole purpose of trying to help users understand their choices and hopefully solve their issues and all for FREE, in hopes to "make this world a better place" (this last part is from the Silicon Valley show on TV).

Promoting any of these can easily be done just by mentioning them in the main repository page, take a look at my TabletTest and PhoneTest repos with the "Useful Resources" paragraph on the bottom.

**Comment by GitHubDragonFly** [comment]
In case if you would like to experiment with GUI file, it can be downloaded from my new repo and so far it only has a working code for reading most atomic types and strings and getting tags from ControlLogix PLC:

https://github.com/GitHubDragonFly/Python_libplctag_GUI

Also, in case if you might be interested, I experimented with pycomm3 to get and list UDT members.
There is a file named `lgx_gui_test.py` here: https://github.com/ottowayi/pycomm3/tree/master/examples

The tag listing produced by the pycomm3 looks like in the attached file.

![Tags - List Box](https://user-images.githubusercontent.com/69928501/106382870-50fb0280-6390-11eb-818d-c8493b94ab6f.png)

I will go ahead and close this issue.

**Comment by kyle-github** [comment]
Great stuff!   No worries if you want to keep going in your own repo.   

Can I keep this open as a reminder to update the README to point to your repo?  

I am still working with the new core and it is fighting back.   Just got raw CIP to work by pulling some tag definitions.   Next up is testing getting UDT definitions.

**Comment by GitHubDragonFly** [comment]
Keep this open for as long as you want.

Whenever I manage to create a new repo then I will eventually post the link here.

**Comment by GitHubDragonFly** [comment]
Pydroid 3 app on Android devices can run this project with your library.
GUI file has to be opened in the IDE and run from there (terminal doesn't support running GUI).
Depending on the Android device and its resolution, one might need to make size and placement adjustments to widgets used in the GUI file.

I have updated the folder structure picture and the libplctag.py file in my initial post.

**Comment by GitHubDragonFly** [comment]
There also seems to be another way of making things work and not only on Android:

https://github.com/dmroeder/pylogix/issues/137

With respect to using your library on Android, I still find my apps to currently have the best approach.

**Comment by kyle-github** [comment]
Ooh, thanks for the link!

Yeah, there has to be a better way.   I just found out that JFrog is going to wind down the bintray project and thus all my hosting for an Android package.   I think I may just give up in disgust trying to get it fully into the Android ecosystem and just build my own packages as you said :-/

**Comment by GitHubDragonFly** [comment]
The libplctag4android project is already set to clone the latest "prerelease" branch.

If you change it to point to the "release" branch then you can easily get the packages ready.

I still think that you could create another Android project for creating AAR, just like it was discussed in the libplctag4android project. I usually update it in my repos so you can always get it from there instead.

**Comment by GitHubDragonFly** [comment]
Even though this is still work in progress, I did create a new repo with current GUI file:

https://github.com/GitHubDragonFly/Python_libplctag_GUI

Also, check the libplctag.py file in the first post since I did update it to include string data accessor functions, for which I am not completely sure if everything is correct and how they need to be used.

**Comment by GitHubDragonFly** [comment]
There is also a new repo with VB Net app for Windows, that can be used for testing:

https://github.com/GitHubDragonFly/AB-Modbus-Master

**Comment by kyle-github** [comment]
Ooh, nice work!

**Comment by kyle-github** [comment]
Unfortunately, I am not a Python programmer, so I am not sure if the Python for the string handling is right or not :-(

**Comment by GitHubDragonFly** [comment]
I did update libplctag.py again and do get all the string functions return correct values, with these excerpts of the python code (just in case if somebody might need it):

import platform
pythonVersion = platform.python_version()

tagValue = Label(frame3, text='~', fg='yellow', bg='navy', font='Helvetica 24', width=33, relief=SUNKEN)

#---------------------------------------
global stringValue

stringLength = plc_tag_get_string_length(tagID, 0) 
stringCapacity = plc_tag_get_string_capacity(tagID, 0) 
stringTotalLength = plc_tag_get_string_total_length(tagID, 0) 

stringValue = str('\0' * (stringLength + 1))
if int(pythonVersion[0]) >= 3:
    stringValue = stringValue.encode('utf-8') # it doesn't show as such but this line requires indentation

response = plc_tag_get_string(tagID, 0, stringValue, stringLength)

tagValue['text'] = ''.join(map(chr, stringValue))
#----------------------------------------

**Comment by GitHubDragonFly** [comment]
Here is a few more bit/bool functions that I missed to put in the libplctag.py file, approximately at line 338 just above the #String:

# Bit/Bool
def plc_tag_get_bit(tag, offset):
    return plcTagGetBit(tag, offset)

def plc_tag_set_bit(tag, offset, value):
    return plcTagSetBit(tag, offset, value)

# String

You can probably update it yourself so I don't have to put a PR in.

**Comment by GitHubDragonFly** [comment]
I consider this done currently so you can close this issue whenever you are ready.

The app is finished so give it a try (and also try not to report a bug).

**Comment by kyle-github** [comment]
Nice work on that app!   That is really a good test/demonstrator! 

I am getting pretty close to supporting UDT definitions now too.   See issue #231 for tracking.

I'll close this now.

**Comment by GitHubDragonFly** [comment]
@kyle-github just in case if you might be interested, there is a special version of this running on the iMac PowerPC and with the library v2.1.17 compiled from the source:

https://github.com/GitHubDragonFly/Python_libplctag_Mac_PPC
