### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_libplctag)

### ISSUE THREAD

**Issue by hussainkadori** [libplctag/libplctag#254]
Hi,
I have an import error with the python wrapper:

```
from plctag import libplctag
ImportError: dynamic module does not define module export function (PyInit_libplctag)
```
I am using python 3.9.2

**Comment by GitHubDragonFly** [comment]
It should be:   from libplctag import *

Is "plctag" something that you created?

You should check this project to make sure that you know how to reference things:

   https://github.com/GitHubDragonFly/PythonTest

**Comment by hussainkadori** [comment]
@GitHubDragonFly I tested your gui and I have the same error:
```
    from libplctag import *
ImportError: dynamic module does not define module export function (PyInit_libplctag)
```

**Comment by hussainkadori** [comment]
I solved the problem when I built the library on fedora and there is two files **libplctag.so** and **libplctag.so.2.3** , I was loading the libplctag.so instead of libplctag.so.2.3. 

Thanks

**Comment by kyle-github** [comment]
Please reopen if you still find a problem!
