### ISSUE TITLE
Can Mitsubishi PLC module be connected? 

### ISSUE THREAD

**Issue by byeondwl** [libplctag/libplctag#263]
Recently I tried to use libplgtag to connect to Mitsubishi’s QJ71EIP71 communication module. How should I write TAG_PATH? Please provide me with any good suggestions, thank you ！

**Comment by kyle-github** [comment]
This library only supports CIP (Rockwell, Omron) and Modbus.   What protocol does the QJ71EIP71 support?

**Comment by byeondwl** [comment]
> 
> 
> This library only supports CIP (Rockwell, Omron) and Modbus. What protocol does the QJ71EIP71 support?

The QJ71EIP71 module allows MELSEC-Q series modules to connect to the EtherNet/IP network;
Connectivity to the EtherNet/IP network:

1.  Communications using tags (Tag communication);
2.  Cyclic Transmission (Class1 Tag communication);
3. Communications using read/write requests (Class3 Tag communication);
4.  Asynchronous communication without establishing a connection (UCMM Tag communication).

**Comment by kyle-github** [comment]
From what little I can find online, it looks like you should be able to get it to work.  I will happily take patches if you have any.  I do not have a Mitsubishi PLC so I cannot test anything.

Please reopen if you have any questions.
