### ISSUE TITLE
Inconsistent documentation of elem_size on Tag String Attributes wiki page

### ISSUE THREAD

**Issue by Greg-Wood-Australia** [libplctag/libplctag#268]
Under "Optional Generic Attributes" you've written that "elem_size" is ignored for Modbus and for Allen-Bradley PLCs, yet under "AB-Specific Attributes" you've written that "elem_size" is required for some PLC types such as PCCC-based PLCs.

I'm just new to this library, so I thought you might like some feedback from someone who is meeting it for the first time.

**Comment by kyle-github** [comment]
Thanks for pointing this out!  I believe I have fixed the wiki.
