### ISSUE TITLE
Omron-njnx Error when I try to write sint or usint.

### ISSUE THREAD

**Issue by joao147** [libplctag/libplctag#274]
I m using libplctag.NET, I opened this issue there, but bug was not there. A colab said that error can be on core project or with my plc.
This is thee error that is returned using libplctag.NET api.
![image](https://user-images.githubusercontent.com/50873876/125626186-abd82f6f-e98a-40a0-a7e0-6fb25a489340.png)

Same error using native wrapper.
![image](https://user-images.githubusercontent.com/50873876/125626333-6a3da0cf-f254-4648-bdd8-09c7412b6487.png)

**Comment by kyle-github** [comment]
Hi thanks for bringing this up.  Can you run the test with debugging turned in to level 4?  Getting that output will help understand what is happening here.

**Comment by timyhac** [comment]
@joao147 add &debug=4 into the attribute string to do this.

**Comment by kyle-github** [comment]
Hi, have you had any time to try to get a debugging dump?

**Comment by kyle-github** [comment]
You might want to reach out to the forum: https://groups.google.com/g/libplctag

More people read the forum than read these issue reports.   I do not personally use Omron PLCs so I cannot help much without the debugging logs.

**Comment by kyle-github** [comment]
Please reopen this when you are able to get the debug logs.
