### ISSUE TITLE
Python Wrapper .DLL Not Found

### ISSUE THREAD

**Issue by Vexx112** [libplctag/libplctag#276]
Is the Python wrapper still supported for this library? I see in the README.TXT that it “should work”, but upon compiling, Thonny says that libplctag is trying to reference a .dll file that does not exist:

![picture1](https://user-images.githubusercontent.com/88156794/127555381-d105e57f-d1aa-45b1-b763-b16a15d8ffa3.png)

**Comment by GitHubDragonFly** [comment]
You should read the note that is just above the code you posted.

If the file could not be found then nobody put it there.

**Comment by kyle-github** [comment]
As @GitHubDragonFly noted, you need to install the C DLL first.   Once it is installed where Python will find it, then the Python code should work.

If you need a pure Python solution, I strong suggest looking at the pylogix or pycomm3 projects on GitHub.  They are really nice and well maintained.   The authors of those projects and I regularly exchange ideas and they are great to work with!

**Comment by kyle-github** [comment]
I have tested this on Linux and it finds the DLL just fine in ubuntu_x64. 

Just copy the C DLL into the correct directory and it will be found.  It looks like this is on Windows.  If it is 64-bit x86 Windows, then use the windows_x64 directory and copy plctag.dll into it.

Please reopen if this does not work for you!
