### ISSUE TITLE
Omron Performance

### ISSUE THREAD

**Issue by mad93** [libplctag/libplctag#309]
Hi Kyle,

This documentation is related to a software provided by omron, a server to communicate with NJ PLCs.

This document can be downloaded from https://klinkmann.ru/download/?file=6988&el=16619&section=klinkmann

And here is a more reliable document about CIP on NJ501 and NJ301 https://www.kepware.com/getattachment/cb87974e-d7e9-44fb-8de3-32aa71958cff/omron-nj-ethernet-manual.pdf

Here the say tha the maximum is 1996 bytes (as seen before).

I must say that in this last document talks about huge array adquisition, but with my testing I've been only allowed to request arrays of 125 DINT in the PLC. If the variable on the PLC is holding more than 125 DINTs, when requested the array the PLC responds that the variable is too large to be supplied.

> Block sizes are specified as an element count. A block size of 120 elements means that a maximum of 120 array
> elements will be read in one request. The maximum block size of 3840 elements means a maximum of 3840 array
> elements will be read in one request

Also adding this manual that defines CIP commands implemented (from page 1025 on pdf, real 1081) https://assets.omron.eu/downloads/manual/en/v4/w502_nx_nj-series_instructions_reference_manual_en.pdf

Finally I also link a document where are defined the error codes definition and how to solve them https://www.kepware.com/getattachment/695831fb-d34f-4c4f-96a8-771d1f36574d/omron-nj-ethernet-manual.pdf

**Comment by kyle-github** [comment]
Thanks for this great documentation!  Perhaps the Omron PLCs will be the best documented ones now!

I will read through these and see what changes I need to make.

I have some performance problems with Modbus to solve more urgently than this, but I should get to this soon.
