### ISSUE TITLE
comunicacion con rslinx emulate500

### ISSUE THREAD

**Issue by InofensivoJimmy** [libplctag/libplctag#319]
Quiero comunicarme con un tag con el nombre TAG_PRUEBA de tipo bool. Utilizo el elmulador rslinx emulate500 para hacer la prueba.
Using library version 2-3-4
"protocol=ab-eip&gateway=192.168.18.16&path=1,2&plc=ControlLogix&elem_size=4&elem_count=1&name=TAG_PRUEBA",TIMEOUT)
no tengo claro elem_size, ni siquiera si es necesario ponerlo. ver

**Comment by lpc921** [comment]
Emulator doesn't provide the CIP interface. You need a real PLC or SoftLogix.

**Comment by kyle-github** [comment]
Thanks @lpc921!

Please reopen if there are further questions.

**Comment by TheFern2** [comment]
> Emulator doesn't provide the CIP interface. You need a real PLC or SoftLogix.

Actually, this isn't entirely true. Emulator does provide a cip interface but only on localhost. With that being said I haven't tested with libplctag.

Have a look here https://github.com/dmroeder/pylogix/issues/23
