### ISSUE TITLE
How to read/write to UDT type?

### ISSUE THREAD

**Issue by skyrobos** [libplctag/libplctag#320]
Hi, 
I need to get access to field some_tag:O.inner_filed
 The some_tag has 20 more fields, and I need access(read/write) to some some of them.
I've tried to use this path protocol=ab_eip&gateway=<MY_PLC_IP>&path=1,0&cpu=LGX&elem_size=1&elem_count=1&name=some_tag:O.inner_filed"
but it didn't worked

**Comment by skyrobos** [comment]
It supposes to work like this. I had an error on my side

**Comment by kyle-github** [comment]
What was the correct tag name?

**Comment by skyrobos** [comment]
name=some_tag:O.inner_filed
