### ISSUE TITLE
Access Violation error

### ISSUE THREAD

**Issue by tneon1** [libplctag/libplctag#322]
i am updating a project that was working fine with Libplctag version 1.0.4, but once I updated to the current version I started getting intermittent access violation errors . When these violation happen my try/catch would not catch the errors. I am not sure why the try/catch is not catching the error.  the class is being called from a on timed event in another project. I have attached a text copy of the class library that I am using. Also what are the best practices wen using libplctag.
Thank you for any insight you can provide
 
Thank You
[Libplctag issue.docx](https://github.com/libplctag/libplctag/files/7705312/Libplctag.issue.docx)

**Comment by kyle-github** [comment]
What wrapper are you using?  It looks like C#.  The C programming language does not have try/catch, so you definitely are not using the C DLL directly.

Did you look for similar issues on the [C# wrapper site](https://github.com/libplctag/libplctag.NET)?  Jody and Tim can probably help you more than I can.

**Comment by timyhac** [comment]
In terms of why you aren't seeing an exception this seems to be a question about how async/await and Tasks work, as opposed to libplctag. Here is some reading:
* https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#asynchronous-exceptions
* https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library
* https://stackoverflow.com/a/15203282

In terms of the Access Violation Error, are you able to provide a minimal example of what is causing the error

**Comment by tneon1** [comment]
Sorry,

I am using C# libplctag wrapper.
My project is a c# project as well

I have narrowed it down to a fix for bools not reading. The tag appears to sometimes be null. I added the class within my projects name space. It only happens on the bool tag write.

 public class CustomBoolPlcMapper : IPlcMapper<bool>
    {

        public int? ElementSize => 1;

        public PlcType PlcType { get; set; }
        public int[] ArrayDimensions { get; set; }

        public int? GetElementCount() => 1;

        bool IPlcMapper<bool>.Decode(Tag tag) => tag.GetUInt8(0) == 1;

        void IPlcMapper<bool>.Encode(Tag tag, bool value) => tag.SetUInt8(0, value == true ? (byte)1 : (byte)0);
    }

**Comment by tneon1** [comment]
I will post on the wrapper site 
Thanks

**Comment by kyle-github** [comment]
Closing this in favor of [#226](https://github.com/libplctag/libplctag.NET/issues/226) on the .Net wrapper site.
