### ISSUE TITLE
PLC5 dhrio bridge broken in v2.4.6

### ISSUE THREAD

**Issue by ngx45** [libplctag/libplctag#324]
Hi Kyle,

PLC5 dhrio bridge broken in version 2.4.6

libplctag_2.4.6_windows_x86\Release>tag_rw.exe  -t sint16  -p "protocol=ab_eip&gateway=192.168.1.103&path=1,3,B:13:2&cpu=PLC5&elem_size=2&elem_count=1&name=n7:0"
Library version 2.4.6.
Arg[0]=tag_rw.exe
Arg[1]=-t
Arg[2]=sint16
Arg[3]=-p
Arg[4]=protocol=ab_eip&gateway=192.168.1.103&path=1,3,B:13:2&cpu=PLC5&elem_size=2&elem_count=1&name=n7:0
ERROR PLCTAG_ERR_TIMEOUT: error creating tag!

Version 2.4.5 OK
libPlcTag\2.4.5\libplctag_2.4.5_windows_x86\Release>tag_rw.exe  -t sint16  -p "protocol=ab_eip&gateway=192.168.1.103&path=1,3,B:13:2&cpu=PLC5&elem_size=2&elem_count=1&name=n7:0"
Library version 2.4.5.
Arg[0]=tag_rw.exe
Arg[1]=-t
Arg[2]=sint16
Arg[3]=-p
Arg[4]=protocol=ab_eip&gateway=192.168.1.103&path=1,3,B:13:2&cpu=PLC5&elem_size=2&elem_count=1&name=n7:0
data[0]=2 (2)
Done

dhrio bridge path, libplctag format: 1,3,B:13:2
1=1756 chassis
3=dhrio slot
B=dhrio ch B
13=dhrio dh+ no octal
2=plc5 dh+ no octal

Regards,
ngx

**Comment by kyle-github** [comment]
You have found a bug!   It looks like I manage to break this while changing the logic for how packet sizes are negotiated for Omron.   I will add this to the test suite to avoid future breakage and roll out a release as soon as possible.

- [x] set flag to use old ForwardOpen for PCCC PLCs.
- [x] add DH+ bridging to tests.

**Comment by kyle-github** [comment]
Fixed in the latest release v2.4.7.
