### ISSUE TITLE
Tag string writing

### ISSUE THREAD

**Issue by InofensivoJimmy** [libplctag/libplctag#333]
I use the libplctrag4j library. I would like to know the correct way to write on a tag of type string, because sometimes the result is not the desired one

is this correct?
tag4.SetString(0,"value")
tag4.Write(TIMEOUT)

**Comment by kyle-github** [comment]
Please open this on the [libplctag4j issues page](https://github.com/libplctag/libplctag4j/issues).

**Comment by kyle-github** [comment]
Moved over to libplctag4j.
