### ISSUE TITLE
Continuous tag reading

### ISSUE THREAD

**Issue by InofensivoJimmy** [libplctag/libplctag#334]
To continuously display the value of some tags, I use the following instruction:

	tag2.Read(TIMEOUT)
	tag3.Read(TIMEOUT)
	tag4.Read(TIMEOUT
	
        val2 = tag2.GetInt32(0)
	LabelTAG_INT.Text = val2
	
	val3 = tag3.GetFloat32(0)
        LabelTAG_REAL.Text = NumberFormat(val3,0,1)
	
	val4 = tag4.GetString(0)
	LabelTAG_STRING.Text = val4

instructions that repeat within a loop, it works fine, but is this the correct way? 
make constant read calls, affect the performance of the computer?

the language is B4X, and it is a wrapper for this platform, but it is still in testing. Thank you
https://www.b4x.com/

**Comment by kyle-github** [comment]
Moved over to libplctag4j.
