### ISSUE TITLE
Clarification about callback unregistration

### ISSUE THREAD

**Issue by kpreisser** [libplctag/libplctag#352]
Hi, sorry if this is not the appropriate place to open this. I have a question about unregistration of callbacks which is not clear from the documentation:

The [Wiki](https://github.com/libplctag/libplctag/wiki/API#callbacks) mentions the `plc_tag_unregister_callback` to unregister a callback, and also mentions that a callback might be called from a library thread.
Is the previously registered callback guaranteed to **not** be still called/executed once `plc_tag_unregister_callback` returns? E.g. in case a callback would be called in a library thread, does this function wait until the callback was executed (if the callback is just about to be called or is currently executing), or could it happen that the callback is still called after `plc_tag_unregister_callback` returns?

This would is important to know when using the callback registration with user data (`plc_tag_register_callback_ex`, #345), as for example in .NET you can use a [function pointer](https://devblogs.microsoft.com/dotnet/improvements-in-native-code-interop-in-net-5-0/#function-pointers) to a static method (for optimal performance), and then use a [`GCHandle`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandle?view=net-6.0) to map a .NET object to a pointer (`IntPtr`) which you can then use in the static callback method to map the pointer back to the .NET object.
For this, you would allocate the `GCHandle` before calling `plc_tag_register_callback_ex`, and free it after calling `plc_tag_unregister_callback`. However, if the callback could still be called after that function returns, the `GCHandle` might already be freed and this might cause invalid memory access in the callback function.

I also found issue libplctag/libplctag.NET#235, but it doesn't seem to answer this either.

Thank you!

**Comment by kpreisser** [comment]
From what I understand when looking at the C code (but please note I'm not a C programmer so I might not interpret it correctly), the `plc_tag_unregister_callback` function locks at the tag's `api_mutex` in order to clear  `tag->callback`:

https://github.com/libplctag/libplctag/blob/6069f39eb5109ed9aca49c978731957e3a23dca1/src/lib/lib.c#L1130-L1156

However, in `THREAD_FUNC` (which I assume is called from a library thread), it looks like it first locks on the tag's `api_mutex`, but then releases the lock and then calls the callbacks (outside of the lock):
https://github.com/libplctag/libplctag/blob/6069f39eb5109ed9aca49c978731957e3a23dca1/src/lib/lib.c#L570-L574

https://github.com/libplctag/libplctag/blob/6069f39eb5109ed9aca49c978731957e3a23dca1/src/lib/lib.c#L385-L397

Do I understand correctly that this can mean that the callback could still be called after `plc_tag_unregister_callback` returns?

For example, if the thread that is currently executing `plc_tag_generic_handle_event_callbacks()`  is at the point where it has read the `tag->callback` value (that is not yet `NULL`) and is just about to call that function, and before that happens, another (application) thread calls `plc_tag_unregister_callback`, which enters the mutex, clears the callback, and returns. If then the library thread continues, it would still call the callback function (through the previously read `tag->callback` value) even though `plc_tag_unregister_callback` already returned previously in the other thread.

Thanks!

**Comment by kpreisser** [comment]
[**Edit:** Sorry, I noticed I was looking at the wrong branch previously.]
In branch `prerelease` which contains the new `userdata` functionality, it looks like the callbacks that may be called from the library thread (in `plc_tag_generic_handle_event_callbacks`) are called within a lock on the tag's `api_mutex`. Because `plc_tag_unregister_callback` also locks on that mutex, it should be guaranteed that once `plc_tag_unregister_callback` returns, the callback can no longer be executed, so this should be safe (at least when you are not calling APIs for the same tag by different threads at the same time):

https://github.com/libplctag/libplctag/blob/304d304b309b9b7ac9c8da475f6d8ad428d662ff/src/lib/lib.c#L388-L401

https://github.com/libplctag/libplctag/blob/304d304b309b9b7ac9c8da475f6d8ad428d662ff/src/lib/lib.c#L1233-L1253

However, there are some places where the tag callback seems to be called outside of the lock on the tag's `api_mutex` (but inline from the calling application thread), for example in `plc_tag_abort`:
https://github.com/libplctag/libplctag/blob/304d304b309b9b7ac9c8da475f6d8ad428d662ff/src/lib/lib.c#L1426-L1464

As far as I understand it, this could mean that when one (application) thread calls `plc_tag_abort` for a specific tag, but at the same time another (application) thread calls `plc_tag_unregister_callback` for the same tag, it could happen that `plc_tag_unregister_callback` returns but then the tag callback is still called (in the other application thread).

**Comment by kyle-github** [comment]
It all should be safe, but I still need to walk through all the possible code paths before I release 2.5.0.  I had to make the mutexes recursive which means that it is possible for a single thread of control to call the removal of the callback while within the callback.  

This is one of the many things that need to be refactored.  There are too many areas where such access is not enforced and should be.   I have some ideas here but need to do some testing first.

And yes, it is possible that events can be raised somewhat out of order in some circumstances.  That is the nature of the asynchronous core.

**Comment by kyle-github** [comment]
If you do find a location that is not guarded by the mutex, please let me know!  Hopefully I have not missed one.  More eyes on the code is always welcome!

I will be writing some tests to use a lot of threads and add/remove callbacks often.

**Comment by kyle-github** [comment]
The change to use recursive mutexes prevents other threads from calling these API functions in dangerous ways but it open up the possibility of unregistering the callback from within a callback call chain.   

I will add some checks to help catch that case, but there are instances where this is going to be a problem.   I will look through the call chains possible to see if I can come up with ways to call the API functions, generate a callback and call through NULL or call with a NULL user data pointer.

**Comment by kyle-github** [comment]
It looks like I need to figure out possible compiler changes to code order.   In some circumstances, the compiler can legally reorder the execution.  If that could result in a case where the function pointer was not NULL but the user data pointer had been set to NULL, we might have a problem.  I might need another guard there.

**Comment by kpreisser** [comment]
Hi @kyle-github,
thanks for your reply!

> And yes, it is possible that events can be raised somewhat out of order in some circumstances. That is the nature of the asynchronous core.

Yes, I agree it is expected that events may be raised somewhat out of order, doe to the async nature of the library, and that it's the application's responsibility to correctly synchronize this when callbacks are concurrently called by different threads. At the same time, I think it's important that the library makes a guarantee when a callback will no longer be called (e.g. after `plc_tag_unregister_callback` returns), so that an application can correctly manage the memory that is passed as `void* userdata` to the callback, and can safely deallocate the memory after unregistering the callback, without having to worry that the callback might still be called again in another thread. This guarantee seems currently to be the case for the callbacks called by `plc_tag_generic_handle_event_callbacks`, as they are called within the lock on the tag's `api_mutex`, and `plc_tag_unregister_callback` also locks on that mutex.

However, about the example with `plc_tag_abort` (which I added in my last post later), as far as I understand it, `plc_tag_abort` currently still calls the `tag->callback` outside of the lock on `tag->api_mutex`, and this could mean that if the application calls `plc_tag_abort` in thread A, and at the same time calls `plc_tag_unregister_callback` in thread B for the same `tag_id`, it could happen that `plc_tag_unregister_callback` returns in thread B, but after that, the `tag->callback` is still called in thread A (from within `plc_tag_abort`).

Is this expected behavior? AFAIU, this woud imply that the user/application must never concurrently call functions for the same `tag_id` by two different threads at the same time (i.e. there is no thread-safety for a specific tag instance).
Or maybe should the callback also be called within the lock on `api_mutex` in these cases? Because the Wiki currently says:
> The library is designed for multi-threaded use.

Thank you!

**Comment by kyle-github** [comment]
I have updated the prerelease branch to handle all the instances where the callback was called directly.

I convinced myself that the compiler will not reorder the stores within a single thread.   It is not clear to me whether a recursive mutex acts as a memory barrier within a single thread but if the compiler reordered stores in that circumstance, it would break regular single threaded code.
