### ISSUE TITLE
add parameters to Makefile

### ISSUE THREAD

**Issue by ronytesler** [libplctag/libplctag#355]
I have a code in c that I now compile like this:
gcc -std=c11 -pthread test.c -o test `pkg-config --cflags --libs libsystemd`

I want to modify one of the example files to include my code, let's say simple.c.
How can I add these settings to the existing Makefile?

**Comment by kyle-github** [comment]
If you want to include libplctag in your build process, add libplctag to the libraries list and include libplctag.h in the files that use the library functions.

```text
gcc -std=c11 -pthread -lplctag test.c -o test `pkg-config --cflags --libs libsystemd`
```

The library needs to be installed where gcc can find it such as /usr/local/lib or you can pass flags to gcc to tell it where to search, and the include file needs to be installed where it can be found too.

**Comment by ronytesler** [comment]
I just manged to do it. I though I needed to do something with the make file, but I just copied the libplctag output files to /usr/lib and compiled with gcc -std=c11 -pthread -lplctag test.c -o test `pkg-config --cflags --libs libsystemd` and it worked.
Thanks!
