### ISSUE TITLE
Need clarification on addressing mechanism used for ControlLogix

### ISSUE THREAD

**Issue by Pravin044** [libplctag/libplctag#359]
Hi guys, i need some clarification on which addressing mechanisum is using for controllogix is it a just symbolic reference or logical/ physical address mapping

**Comment by kyle-github** [comment]
Symbolic addressing is used for Control/CompactLogix.   For PLC/5, SLC 500, and MicroLogix, DF1-style logical addressing is used.

**Comment by Pravin044** [comment]
Thanks for the information
