### ISSUE TITLE
Connect to OpenPLC Ethernet/IP soft-plc

### ISSUE THREAD

**Issue by pjbonestroo** [libplctag/libplctag#375]
Before buying a Allen Bradley PLC I would like to use libplctag in my development environment to connect to a [OpenPLC](https://openplcproject.com/) device, which I can install as soft-plc. Do you think this is possible? Or what need to be done before this is possible? I tried it already (using libplctag by python) but I get errors when creating tags. I didn't dive into the errors yet, but first wanted to know from someone more experienced if I'm trying something feasible or not.

**Comment by kyle-github** [comment]
You should probably raise this question in the [forum](https://groups.google.com/g/libplctag).   There are over 300 people that see those posts.

I do not use OpenPLC.   It looks interesting.

**Comment by pjbonestroo** [comment]
@kyle-github Thanks, I've requested to participate in the forum.
