### ISSUE TITLE
Async tag creation skips raising created event.

### ISSUE THREAD

**Issue by kyle-github** [libplctag/libplctag#404]
It looks like creating a tag without a timeout in plc_tag_create_ex() will skip raising the created event.   

- [x] Trigger PLCTAG_EVENT_CREATED when first read is done in all CIP tags.
- [x] Trigger PLCTAG_EVENT_CREATED when first read is done in Modbus tags.
- [x] Suppress PLCTAG_EVENT_READ_STARTED when first read is triggered.  Only CIP tags.
- [x] Add tests to check that CREATED event is coming in with PLCTAG_STATUS_OK.

**Comment by kyle-github** [comment]
Brought up from libplctag.Net issue [304](https://github.com/libplctag/libplctag.NET/issues/304).

**Comment by kyle-github** [comment]
Raising the PLCTAG_EVENT_CREATED event always at the end of plc_tag_create_ex() ends up raising events that are not OK (still PENDING).   So we need some method of triggering a PLCTAG_EVENT_CREATED with a status of OK.

**Comment by timyhac** [comment]
This all seems to be working as expected now. I've done testing with some mixed network availability (the modbus server container was either running or not) and got the expected results.
