### ISSUE TITLE
Modbus teardown does not complete

### ISSUE THREAD

**Issue by kyle-github** [libplctag/libplctag#405]
See issue [#312](https://github.com/libplctag/libplctag.NET/issues/312) in the .Net project.   This may be a core DLL problem.

**Comment by kyle-github** [comment]
Version 2.5.5 has an attempt at fixing this.  `plc_tag_shutdown()` is extended to destroy all tags and to be called through the `atexit()` hook and through Windows' `DllMain()` hook.

**Comment by timyhac** [comment]
Yep this looks good now, I haven't been able to repeat the problem when trying to with the same steps.

**Comment by kyle-github** [comment]
Thanks for testing @timyhac!

I'll aim to release this set of fixes either later today or tomorrow.
