### ISSUE TITLE
Build with Mingw32 fails - #warning Please include winsock2.h before windows.h

### ISSUE THREAD

**Issue by nurquhar** [libplctag/libplctag#407]
I tried a clone and build of 2.5.5 with the following commands on my Windows 11 m/c setup with Mingw32

mkdir Build
cd Build
cmake -G "MinGW Makefiles" ..
mingw32-make

This is what version of GCC I have installed

`$ gcc --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

But mingw32-make step gives compilation errors, this is the last bit : 

`C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:139:12: warning: inline function 'StringCatNExWorkerA' declared but never defined
 STRSAFEAPI StringCatNExWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCSTR pszSrc,size_t cchToAppend,STRSAFE_LPSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:138:12: warning: inline function 'StringCatNWorkerW' declared but never defined
 STRSAFEAPI StringCatNWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,STRSAFE_LPCWSTR pszSrc,size_t cchToAppend);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:137:12: warning: inline function 'StringCatNWorkerA' declared but never defined
 STRSAFEAPI StringCatNWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,STRSAFE_LPCSTR pszSrc,size_t cchToAppend);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:136:12: warning: inline function 'StringCatExWorkerW' declared but never defined
 STRSAFEAPI StringCatExWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCWSTR pszSrc,STRSAFE_LPWSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:135:12: warning: inline function 'StringCatExWorkerA' declared but never defined
 STRSAFEAPI StringCatExWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCSTR pszSrc,STRSAFE_LPSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:134:12: warning: inline function 'StringCatWorkerW' declared but never defined
 STRSAFEAPI StringCatWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,STRSAFE_LPCWSTR pszSrc);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:133:12: warning: inline function 'StringCatWorkerA' declared but never defined
 STRSAFEAPI StringCatWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,STRSAFE_LPCSTR pszSrc);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:132:12: warning: inline function 'StringCopyNExWorkerW' declared but never defined
 STRSAFEAPI StringCopyNExWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCWSTR pszSrc,size_t cchToCopy,STRSAFE_LPWSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:131:12: warning: inline function 'StringCopyNExWorkerA' declared but never defined
 STRSAFEAPI StringCopyNExWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCSTR pszSrc,size_t cchToCopy,STRSAFE_LPSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:130:12: warning: inline function 'StringCopyNWorkerW' declared but never defined
 STRSAFEAPI StringCopyNWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,STRSAFE_LPCWSTR pszSrc,size_t cchToCopy);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:129:12: warning: inline function 'StringCopyNWorkerA' declared but never defined
 STRSAFEAPI StringCopyNWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,STRSAFE_LPCSTR pszSrc,size_t cchToCopy);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:128:12: warning: inline function 'StringCopyExWorkerW' declared but never defined
 STRSAFEAPI StringCopyExWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCWSTR pszSrc,STRSAFE_LPWSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:127:12: warning: inline function 'StringCopyExWorkerA' declared but never defined
 STRSAFEAPI StringCopyExWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,size_t cbDest,STRSAFE_LPCSTR pszSrc,STRSAFE_LPSTR *ppszDestEnd,size_t *pcchRemaining,unsigned __LONG32 dwFlags);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:126:12: warning: inline function 'StringCopyWorkerW' declared but never defined
 STRSAFEAPI StringCopyWorkerW(STRSAFE_LPWSTR pszDest,size_t cchDest,STRSAFE_LPCWSTR pszSrc);
            ^
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/strsafe.h:125:12: warning: inline function 'StringCopyWorkerA' declared but never defined
 STRSAFEAPI StringCopyWorkerA(STRSAFE_LPSTR pszDest,size_t cchDest,STRSAFE_LPCSTR pszSrc);
            ^
[ 15%] Building C object CMakeFiles/plctag_dyn.dir/src/platform/windows/platform.c.obj
In file included from C:/Users/neil/Documents/NuSoftLtd/Projects/RoutesReports/NR-MPV-SITT-RHTT-Jan2020/MPV-Vehicles/PLC-Dev/Software/Prototype/Sandpit/Build/Mingw32/libplctag/src/platform/windows/platform.h:54:0,
                 from C:\Users\neil\Documents\NuSoftLtd\Projects\RoutesReports\NR-MPV-SITT-RHTT-Jan2020\MPV-Vehicles\PLC-Dev\Software\Prototype\Sandpit\Build\Mingw32\libplctag\src\platform\windows\platform.c:38:
C:/Users/neil/.platformio/packages/toolchain-gccmingw32/i686-w64-mingw32/include/Winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
  ^
C:\Users\neil\Documents\NuSoftLtd\Projects\RoutesReports\NR-MPV-SITT-RHTT-Jan2020\MPV-Vehicles\PLC-Dev\Software\Prototype\Sandpit\Build\Mingw32\libplctag\src\platform\windows\platform.c:47:21: fatal error: timeapi.h: No such file or directory
compilation terminated.
CMakeFiles\plctag_dyn.dir\build.make:435: recipe for target 'CMakeFiles/plctag_dyn.dir/src/platform/windows/platform.c.obj' failed
mingw32-make[2]: *** [CMakeFiles/plctag_dyn.dir/src/platform/windows/platform.c.obj] Error 1
CMakeFiles\Makefile2:141: recipe for target 'CMakeFiles/plctag_dyn.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/plctag_dyn.dir/all] Error 2
makefile:134: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
`

What am I doing wrong ?

**Comment by kyle-github** [comment]
MinGW is not a a tier 1 platform for libplctag.   All support has been done by contributions from users.   Please ask this question in the [forum](https://groups.google.com/g/libplctag) as there will be a lot more people looking at it and you are likely to get more support.

The library does build with Visual Studio's compilers, and those are free.  It is possible to build 32-bit binaries with those (they are part of the standard release).  I use the Microsoft compilers to build 64-bit x86, 32-bit x86, 64-bit ARM and 32-bit ARM binaries.
