### ISSUE TITLE
force to link again sanitizer when using DEBUG version

### ISSUE THREAD

**Issue by vrince** [libplctag/libplctag#423]
Hi,

This is really great to use Google sanitizers and all. Still, when using the `libpcltag` project "inside" another project, when you build in debug, it also forces you to like against `asan` library or worse compile with `-fsanitize=address -fsanitize=leak -fsanitize=undefined`.

Using sanitizer should be an option (`ON` by default not to change current behavior) so integration of this lib in other projects stays minimally invasive.

Any thoughts?

I think I can provide a PR if you think it should be that way.

Best,

**Comment by kyle-github** [comment]
As I mentioned in the PR, I want to understand why you would want to turn off the sanitizers in a debug build.

**Comment by kyle-github** [comment]
I have marked this as an enhancement and as critical because of your explanation.  Now that I'll have more time, I will try to get this soon.  Sorry for the delay!

**Comment by kyle-github** [comment]
I've merged your PR into the prerelease branch.   I want to see if I can make it work with both gcc and clang before I release.

**Comment by kyle-github** [comment]
This was fixed in v2.5.6.
