### ISSUE TITLE
Write MyTag[1] error

### ISSUE THREAD

**Issue by eslinan** [libplctag/libplctag#429]
I start ab_server, and use pylogix to write tag like this is Ok:
from pylogix import PLC
with PLC() as comm:
    comm.IPAddress = '127.0.0.1'
    value = [1, 2, 3, 4, 5]
    comm.Write('MyTag', value)

but when I write to MyTag[1], it does nothing, why? Thank you.

**Comment by timyhac** [comment]
Hi @eslinan - welcome to the community.

pylogix is obviously a [separate project](https://github.com/dmroeder/pylogix), but assuming you're asking about ab_server - you might need to provide some more information about what you're expecting to happen, and what is actually happening.

On the sister project libplctag.NET we have some guidance on how to create an issue - see https://github.com/libplctag/libplctag.NET/blob/master/CONTRIBUTIONS.md#guidance-when-creating-an-issue

**Comment by eslinan** [comment]
I want to write a list to tag begin with index 4, not index 0.

**Comment by kyle-github** [comment]
As Tim noted, this is for a different project than libplctag.  Please open a ticket there or join the pylogix Discord server.  Dustin (the Pylogic author) is a great guy and more than happy to help with all kinds of questions.

**Comment by kyle-github** [comment]
Closing.
