### ISSUE TITLE
Unknown data type DT

### ISSUE THREAD

**Issue by joed74** [libplctag/libplctag#436]
I cannot read DateTime (DT) fields in my CLX plc:

2023-09-15 16:27:27.822 thread(3) tag(0) INFO unpack_response:1651 00048 00 00 **c0** 00 63 94 90 97 66 05 06 00
2023-09-15 16:27:27.823 thread(2) tag(0) WARN check_read_status_connected:1448 Unsupported data type returned, type byte=**192**

The underlying datatype is just an ULint (or Lint)

I think it has to be added to defs.h

#define AB_CIP_DATA_DT         ((uint8_t)0xC0) /* DT value, 64 bit */

![grafik](https://github.com/libplctag/libplctag/assets/61152521/0278773b-05c0-4a89-a30b-b3a294bc4fa6)

Interestingly, the LDT data type (called STIME in libplctag, type 0xCC) works out of the box

**Comment by kyle-github** [comment]
Unfortunately, the types are not really used anywhere.   Only atomic values seem to be directly supported.

**Comment by kyle-github** [comment]
But I can add this in for what it is worth.

**Comment by kyle-github** [comment]
This should be in the next release.  I really need to find a good list of these type bytes.
