### ISSUE TITLE
Reading 1000 tags using libplctag

### ISSUE THREAD

**Issue by ahmad9918** [libplctag/libplctag#438]
Hello Kyle,

I am trying to use libplctag library to check the performance for read/write operation.
For example if I want to read 1000 tags created in the plc, I would like to know how quickly libplctag library can read 1000 tags and process the response.

Can you please suggest any example or approach how to perform this task. I can see in the wiki page about multi service request packing being supported in the library. I would like to understand how do I trigger read operation which will bring best performance (As fast as possible).

Please share your valuable inputs.
Thanks

**Comment by kyle-github** [comment]
Hi, thanks for using the library.

The library will automatically pack requests together if it has multiple outstanding requests when it is ready to send a packet to the PLC.  

There are two main ways to do this:

1. Create a thread per tag.   This uses many resources on the PC and does not scale up very well, but is sometimes simpler to code.
2. Create multiple tags and access them in async mode.  This allows you to trigger reads/writes on multiple tags very very rapidly and thus queues up multiple requests inside the library.

The async.c example shows how to set up multiple tags and trigger operations within one thread.   This is the highest performance option.  The [wiki page on performance](https://github.com/libplctag/libplctag/wiki/Performance-Tips-with-AB-CIP-based-PLCs) describes this as well.

Please reopen this issue if you need additional details.

**Comment by ahmad9918** [comment]
Hello Kyle,

Thanks for the guidance.

I have tried to test 1000 tags using async.c example and performance was good as it used to pack multiple request in a single packet. I have also observed library is using connected message by default by setting use_connected_msg flag to true which I tried to change by setting to false in order to use unconnected message.
When I tried to run the with use_connected_msg = 0 in debug build it gave below error:

    #0 0x7fd0c41f796a in lock_acquire_try /root/LibPLCTag/libplctag/src/platform/posix/platform.c:952
    #1 0x7fd0c41f79a5 in lock_acquire /root/LibPLCTag/libplctag/src/platform/posix/platform.c:963
    #2 0x7fd0c41f2c89 in rc_dec_impl /root/LibPLCTag/libplctag/src/util/rc.c:225
    #3 0x7fd0c416d6b3 in check_read_status_unconnected /root/LibPLCTag/libplctag/src/protocols/ab/eip_cip.c:1753
    #4 0x7fd0c415b42e in tag_tickler /root/LibPLCTag/libplctag/src/protocols/ab/eip_cip.c:245
    #5 0x7fd0c411a442 in tag_tickler_func /root/LibPLCTag/libplctag/src/lib/lib.c:560
    #6 0x7fd0c344dea6 in start_thread nptl/pthread_create.c:477
    #7 0x7fd0c356aaee in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xfcaee)

I would like to know whether it is possible to use the library with unconnected messaging with Allen Bradley Compact Logix PLC. Also whether the library will pack multi service packet into single packet as it does in connected messaging ?
In terms of performance which will be better among connected messaging and unconnected messaging ? 
Please let me know in case you need any further details.
Thanks
