### ISSUE TITLE
Many "INFO" messages output in command prompt after .AddTag(something) command

### ISSUE THREAD

**Issue by igal92** [libplctag/libplctag#440]
Hello,

First i would like to say thank you very much for the libplctag, its very useful and works great with Allen Bradley PLC.
After adding a second tag using the .AddTag method, the command prompt is being filled up with INFO type log endlessly.
attached picture.
Is there any way to disable this?
![Screenshot 2023-11-19 105250](https://github.com/libplctag/libplctag/assets/71942715/93e6bb0f-9ba8-4cd1-8f80-b8331665f525)

**Comment by kyle-github** [comment]
It looks like you are turning on debugging at some point.   You probably have a line that looks something like this:

`LibPlcTag.DebugLevel = DebugLevel.Detail;`

somewhere in your code.   Remove that.  Or replace it with:

`LibPlcTag.DebugLevel = DebugLevel.None;`

**Comment by kyle-github** [comment]
Please reopen if you still have questions.
