### ISSUE TITLE
Access AB L73 PLC through Private LAN

### ISSUE THREAD

**Issue by fehert89** [libplctag/libplctag#444]
I'm trying to communicate with L73 CLX but I cannot figure out the path to the controller in this case. 

Gateway = 143.26.199.124
I have tried some option for Path but without any success. 

Option1 Path = "1,0,A:192.168.0.102:1,0"
Option2 Path = "1,[0,2,192.168.0.102,1],0"

Is there any way to communicate with the PLC what I have marked on the image below?

![AB](https://github.com/libplctag/libplctag/assets/104865535/c7a02b79-fdb1-4d1f-8281-d8fc20270f90)

**Comment by kyle-github** [comment]
Oops, just noticed this one.   You should be able to access the second PLC using bridging.  The path would be something like:

1,0,18,192.168.0.102,1,0

Breaking this out it is:

1,0 - on the first PLC go to the backplane (1) and to slot zero where the EN2T is.
18,192.168.0.102 - using port 2 on the EN2T (the external port), go to IP 192.168.0.102
1,0 - on the second PLC, go to the backplane and then to slot zero for the CPU module.

Sorry for the delay.  I hope this helps.   Please reopen if you still have problems!
