### ISSUE TITLE
Use Libplctag Library as Server

### ISSUE THREAD

**Issue by aggarwaltapan027** [libplctag/libplctag#446]
Hi,
Is it possible to use Libplctag library as a server. If yes, then please tell the changes which we need to make so that it will work as a server. Actually we have a software that works as a Client, that's why we need to make  a server.

Thanks in Advance

**Comment by kyle-github** [comment]
It is not currently possible.  There is a very, very rudimentary server in the tests directory called ab_server.  It is just a very minimal simulator that supports a few CIP commands that I use for testing when running in the CI system which does not have any PLCs available.

**Comment by aggarwaltapan027** [comment]
Hi,
Can you please share the path of that directory.

Thanks a lot for the reply

Regards

Tapan Aggarwal
