### ISSUE TITLE
MinGW timeapi.h issue

### ISSUE THREAD

**Issue by JKooAllied** [libplctag/libplctag#459]
Hello,

I followed Wiki. After mingw32-make, I am getting this issue: 
libplctag\src\platform\windows\platform.c:48:21: fatal error: timeapi.h: No such file or directory
 #include <timeapi.h>

**Comment by kyle-github** [comment]
Hmm.  It looks like it is missing in some versions of MinGW.  I found this notice on the main MinGW SourceForge site:

https://sourceforge.net/p/mingw-w64/mailman/message/37409800/

That is from 2022.  It looks like timeapi.h should be included with MinGW.   It is one of the header files provided with Visual C/C++ as well.   

When was your version of MinGW created?

**Comment by JKooAllied** [comment]
> Hmm. It looks like it is missing in some versions of MinGW. I found this notice on the main MinGW SourceForge site:
> 
> https://sourceforge.net/p/mingw-w64/mailman/message/37409800/
> 
> That is from 2022. It looks like timeapi.h should be included with MinGW. It is one of the header files provided with Visual C/C++ as well.
> 
> When was your version of MinGW created?

I am using x86_64-win32-seh. I changed Cmake file from -m32 to -m64 in order to make it work with cmake command.
MinGW-W64 GCC-8.1.0

**Comment by kyle-github** [comment]
Based on what I find online, version 8.1 is very old.   Looks like the underlying GCC version is from 2018 which is six year ago.  I would strongly suggest updating MinGW and GCC to the latest version.   There were some problems a few years ago with missing header files in MinGW's version of GCC.

You can find downloads [here](https://www.mingw-w64.org/downloads/).

Is there a reason that you cannot use the free version of Visual Studio?  Microsoft has free downloads and the licensing for the produced binaries is quite reasonable.  With Microsoft's creation of WSL (WLS?) with a Linux environment within Windows, it looks like most of the interest in things like MinGW has dropped.   

My suggestions (in order of preference):

- Use the latest free version of Visual Studio.  It supports CMake out of the box.
- Update to the latest version of MinGW/GCC.  Version 8 GCC is no longer supported by GNU.
- Develop within the WSL environment.  You can use Ubuntu and other flavors of Linux and it is trivial to set up a very solid development environment.   You can cross compile for Windows from that environment but it is not that simple to get working.
-

**Comment by kyle-github** [comment]
Please reopen if you still have a problem.  This question is probably better answered on the [forum](https://groups.google.com/g/libplctag).  There are some people on it who use MinGW.
