### ISSUE TITLE
ASP.Net error

### ISSUE THREAD

**Issue by kaptindan** [libplctag/libplctag#460]
I am trying to use a ASP.Net webpage to read tags. I get an exception error below. 

An exception of type 'System.DllNotFoundException' occurred in libplctag.dll but was not handled in user code
09:05:40:352	Unable to load DLL 'plctag': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by kyle-github** [comment]
Please file this in the [.Net project issues](https://github.com/libplctag/libplctag.NET/issues).  The above error is due to the fact that the DLL is not found in any of the search paths.

**Comment by kyle-github** [comment]
Closing so that it can be opened in the right project.
