### ISSUE TITLE
Minor Documentation Bug for `str_is_fixed_length`

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag#477]
In [Generic String Attributes / str_is_fixed_length](https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes#optional-generic-string-attributes), "84" is not a boolean value - and I think [the split is between Ethernet/IP and Modbus](https://github.com/search?q=repo%3Alibplctag%2Flibplctag+str_is_fixed_length&type=code). 

> AB defaults to 1 (true) for ControlLogix and CompactLogix and 84 for PCCC-based PLCs

**Comment by kyle-github** [comment]
Fixed.  Thanks for noticing!
