### ISSUE TITLE
Unable to read from offsets in Output/Input datafiles on MicroLogix

### ISSUE THREAD

**Issue by CodingJWE** [libplctag/libplctag#479]
I am having trouble reading singular bit values or the entire byte from anything other than the first offset in the input/output data files on a MicroLogix plc. An example of what I am attempting to read can be seen below:

![6415d9f421beab2fc5bf8df2_600c622188abe0dd0c1d1965_uE-QB_Y91QgBGs2pU0Zvp1nRMUZ0WBApOWANjelrcW-_y7e7R8y3VrvUCI8H1AmsPKJh-CHgXi1qhKdN4Qfky_GF3CZpL3bS8P3MW_3ZEUJpYP11pF-2itDYQXomUiHEDPxLDiL2](https://github.com/user-attachments/assets/f78b283a-49fa-4fef-ae6b-ea39de9ae5ec)

Currently, I am only able to access I:0.0, is there a way to access the reset of the offsets? For reference, I am using the following tag names:
- I1:0.1 (does not work)
- I1:0/16 (does not work)
- I1:0 (works, but only for the first offset)

**Comment by CodingJWE** [comment]
I:0.1 and I:0 also do not work

**Comment by kyle-github** [comment]
See issue #481.  I think I fixed the requirement for the data file numbers.   Still not sure what is happening with the offsets though.   Input and Output are not treated quite the same way as "normal" data files in the PLC.  

The code in the library does not handle a number after a ".".   It is looking for a mnemonic (.acc etc.) and translates that into a sub-element number.  

It looks like the code needs to be changed to handle a number after a "." and to use that for the sub-element number.   

I think "I1:0" is working by accident.   It encoded the sub-element as 0 when there is no information about it in the tag string.   In this case there is not, so it defaults to zero.  That is equivalent to I1:0.0.

Let me fiddle with this a bit.  I think I can fix this.
