### ISSUE TITLE
Supported PLC Types for script 'list_tags_logix.c'

### ISSUE THREAD

**Issue by DilaraSer** [libplctag/libplctag#480]
Hello,

I would like to ask which PLC types are supported by the example script 'list_tags_logix.c'. Specifically, does it support both CompactLogix and ControlLogix? Additionally, could you share which PLC types the script has been successfully tested with?

Thank you in advance for your help!

**Comment by kyle-github** [comment]
It supports ControlLogix.  For CompactLogix, you might need to use a path of 0,0.  I do not have one so I cannot test.   It only works with those PLC types.   Micro8x0 does not support the same method of getting UDT definitions so those are not available (yet?) there and there is a separate tool for that.  Omron is in progress but differs much from the Rockwell PLCs.

It should be noted that the tag listing examples are just that; examples.   They are quite minimal and are there for users to see how to get and parse the responses from the "@tags" and "@udt" tag types.  They are definitely not full featured!  The wrapper libraries, especially the .NET wrapper, are more complete.

**Comment by kyle-github** [comment]
If you have other questions, please open another issue.
