### ISSUE TITLE
Functions that are safe to call from callbacks?

### ISSUE THREAD

**Issue by wegel** [libplctag/libplctag#500]
Sorry if this has been answered before or if I somewhat missed it in the documentation:

Are `plc_tag_unregister_callback` and `plc_tag_destroy` safe to be called from callbacks?

Thanks.

**Comment by kyle-github** [comment]
If they are not, it is a bug!   I used to have a test where plc_tag_destroy is called from a different thread than plc_tag_create.   I did a quick check but do not see it now.   Maybe it is part of another test?

**Comment by wegel** [comment]
You've answered my question, thank you.
